version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=test
      - POSTGRES_DB=estuary
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432