version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=test
      - POSTGRES_DB=estuary
    ports:
      - 5432:5432
  redis:
    image: redis:7-alpine
    ports: 
      - 6379:6379